ALTER TABLE orders MODIFY COLUMN due_date DATE NULL;
ALTER TABLE orders MODIFY COLUMN due_time VARCHAR(20) NULL;
ALTER TABLE orders MODIFY COLUMN delivery_method VARCHAR(10) NULL;
ALTER TABLE orders MODIFY COLUMN delivery_address VARCHAR(255) NULL;
