spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/hdsign?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=xkdlrj13!A
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=hdsign-super-secret-key-change-this-32chars
jwt.expiration-ms=86400000
upload.dir=uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

r2.access-key=e6a1d0a811b124a16055f5fab95bf6d5
r2.secret-key=17ec2c5b461763eae498091bac54d37f5eccfcc9d74f6de77d0678aac2b70707
r2.endpoint=https://20e1bfa57c7984e98759840e65610f8f.r2.cloudflarestorage.com
r2.bucket=hdsign-gallery
r2.public-url=https://pub-426f3bd012a0486491f67938ffa1d8f3.r2.dev
